---
title: "USDCNY Day Close Predict"
output: html_document
date: "2023-07-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(tidyverse)
library(caret)
library(glmnet)
library(Metrics)
library(ggsci)
library(readxl)

# 设置工作目录为当前文件夹
setwd(".")

# 构建文件路径
file_path <- file.path("data_csv", "即期汇率_美元兑人民币.csv")
USDCHN_onshore_table <- read.csv(file_path)
colnames(USDCHN_onshore_table) <- c("Time", "USDCHN_onshore")
USDCHN_onshore_table <- USDCHN_onshore_table %>%
  na.omit() %>%
  mutate(Time = ymd(Time))

file_path <- file.path("data_csv", "USDCNH_即期汇率.csv")
USDCHN_offshore_table <- read.csv(file_path)
colnames(USDCHN_offshore_table) <- c("Time", "USDCHN_offshore")
USDCHN_offshore_table <- USDCHN_offshore_table %>%
  na.omit() %>%
  mutate(Time = ymd(Time))

file_path <- file.path("data_csv", "美国_国债收益率_10年.csv")
US_Y10_table <- read.csv(file_path)
colnames(US_Y10_table) <- c("Time", "US_Y10")
US_Y10_table <- US_Y10_table %>%
  na.omit() %>%
  mutate(Time = ymd(Time))

file_path <- file.path("data_csv", "美国_国债收益率_2年.csv")
US_Y2_table <- read.csv(file_path)
colnames(US_Y2_table) <- c("Time", "US_Y2")
US_Y2_table <- US_Y2_table %>%
  na.omit() %>%
  mutate(Time = ymd(Time))

file_path <- file.path("data_csv", "中国十年期国债收益率历史数据.csv")
CHN_Y10_table <- read.csv(file_path)
CHN_Y10_table <- CHN_Y10_table[,1:2]
colnames(CHN_Y10_table) <- c("Time", "CHN_Y10")
CHN_Y10_table <- CHN_Y10_table %>%
  na.omit() %>%
  mutate(Time = ymd(Time))
CHN_Y10_table <- CHN_Y10_table[order(CHN_Y10_table[,1]),]

file_path <- file.path("data_csv", "中国二年期国债收益率历史数据.csv")
CHN_Y2_table <- read.csv(file_path)
CHN_Y2_table <- CHN_Y2_table[,1:2]
colnames(CHN_Y2_table) <- c("Time", "CHN_Y2")
CHN_Y2_table <- CHN_Y2_table %>%
  na.omit() %>%
  mutate(Time = ymd(Time))
CHN_Y2_table <- CHN_Y2_table[order(CHN_Y2_table[,1]),]

file_path <- file.path("data_csv", "沪深300指数.csv")
SH_table <- read.csv(file_path)
colnames(SH_table) <- c("Time", "SH")
SH_table <- SH_table %>%
  na.omit() %>% 
  mutate(Time = ymd(Time))

file_path <- file.path("data_csv", "美国_标准普尔500指数.csv")
SPX_table <- read.csv(file_path)
colnames(SPX_table) <- c("Time", "SPX")
SPX_table <- SPX_table %>%
  na.omit() %>% 
  mutate(Time = ymd(Time))

file_path <- file.path("data_csv", "深证成份指数.csv")
SZI_table <- read.csv(file_path)
colnames(SZI_table) <- c("Time", "SZI")
SZI_table <- SZI_table %>%
  na.omit() %>% 
  mutate(Time = ymd(Time))

file_path <- file.path("data_csv", "美国_纳斯达克综合指数.csv")
IXIC_table <- read.csv(file_path)
colnames(IXIC_table) <- c("Time", "IXIC")
IXIC_table <- IXIC_table %>%
  na.omit() %>% 
  mutate(Time = ymd(Time))

file_path <- file.path("data_csv", "上证综合指数.csv")
SSEC_table <- read.csv(file_path)
colnames(SSEC_table) <- c("Time", "SSEC")
SSEC_table <- SSEC_table %>%
  na.omit() %>% 
  mutate(Time = ymd(Time))

file_path <- file.path("data_csv", "美国_道琼斯工业平均指数.csv")
DJI_table <- read.csv(file_path)
colnames(DJI_table) <- c("Time", "DJI")
DJI_table <- DJI_table %>%
  na.omit() %>% 
  mutate(Time = ymd(Time))

file_path <- file.path("data_csv", "美元指数.csv")
USDX_table <- read.csv(file_path)
colnames(USDX_table) <- c("Time", "USDX")
USDX_table <- USDX_table %>%
  na.omit() %>% 
  mutate(Time = ymd(Time))

file_path <- file.path("data_csv", "现货价_原油_美国西德克萨斯中级轻质原油(WTI).csv")
WTI_table <- read.csv(file_path)
colnames(WTI_table) <- c("Time", "WTI")
WTI_table <- WTI_table %>%
  na.omit() %>% 
  mutate(Time = ymd(Time))

file_path <- file.path("data_csv", "现货价_原油_英国布伦特Dtd.csv")
Dtd_table <- read.csv(file_path)
colnames(Dtd_table) <- c("Time", "Dtd")
Dtd_table <- Dtd_table %>%
  na.omit() %>% 
  mutate(Time = ymd(Time))

file_path <- file.path("data_csv", "现货价_原油(中国大庆)_环太平洋.csv")
Oil_Daqing_table <- read.csv(file_path)
colnames(Oil_Daqing_table) <- c("Time", "Oil_Daqing")
Oil_Daqing_table <- Oil_Daqing_table %>%
  na.omit() %>% 
  mutate(Time = ymd(Time))

file_path <- file.path("data_csv", "现货价_原油(中国胜利)_环太平洋.csv")
Oil_Shengli_table <- read.csv(file_path)
colnames(Oil_Shengli_table) <- c("Time", "Oil_Shengli")
Oil_Shengli_table <- Oil_Shengli_table %>%
  na.omit() %>% 
  mutate(Time = ymd(Time))

file_path <- file.path("data_csv", "基础金价_中国黄金.csv")
CAU_table <- read.csv(file_path)
colnames(CAU_table) <- c("Time", "CAU")
CAU_table <- CAU_table %>%
  na.omit() %>% 
  mutate(Time = ymd(Time))

file_path <- file.path("data_csv", "伦敦现货黄金_以美元计价.csv")
XAU_table <- read.csv(file_path)
colnames(XAU_table) <- c("Time", "XAU")
XAU_table <- XAU_table %>%
  na.omit() %>% 
  mutate(Time = ymd(Time))

file_path <- file.path("data_csv", "期货收盘价(活跃合约)_COMEX黄金.csv")
Au_COMEX_table <- read.csv(file_path)
colnames(Au_COMEX_table) <- c("Time", "Au_COMEX")
Au_COMEX_table <- Au_COMEX_table %>%
  na.omit() %>% 
  mutate(Time = ymd(Time))

file_path <- file.path("data_csv", "期货收盘价(活跃合约)_黄金.csv")
Au_SH_table <- read.csv(file_path)
colnames(Au_SH_table) <- c("Time", "Au_SH")
Au_SH_table <- Au_SH_table %>%
  na.omit() %>% 
  mutate(Time = ymd(Time))

file_path <- file.path("data_csv", "期货官方价_LME3个月铜.csv")
Cu_LME_table <- read.csv(file_path)
colnames(Cu_LME_table) <- c("Time", "Cu_LME")
Cu_LME_table <- Cu_LME_table %>%
  na.omit() %>% 
  mutate(Time = ymd(Time))

file_path <- file.path("data_csv", "期货收盘价(活跃合约)_COMEX铜.csv")
Cu_COMEX_table <- read.csv(file_path)
colnames(Cu_COMEX_table) <- c("Time", "Cu_COMEX")
Cu_COMEX_table <- Cu_COMEX_table %>%
  na.omit() %>% 
  mutate(Time = ymd(Time))

file_path <- file.path("data_csv", "期货收盘价(活跃合约)_阴极铜.csv")
Cu_SH_table <- read.csv(file_path)
colnames(Cu_SH_table) <- c("Time", "Cu_SH")
Cu_SH_table <- Cu_SH_table %>%
  na.omit() %>% 
  mutate(Time = ymd(Time))

merged_table <- USDCHN_onshore_table %>%
  merge(USDCHN_offshore_table, by = c("Time")) %>%
  merge(USDX_table, by = c("Time")) %>%
  merge(US_Y10_table, by = c("Time")) %>%
  merge(US_Y2_table, by = c("Time")) %>%
  merge(CHN_Y10_table, by = c("Time")) %>%
  merge(CHN_Y2_table, by = c("Time")) %>%
  merge(SH_table, by = c("Time")) %>%
  merge(SPX_table, by = c("Time")) %>%
  merge(SZI_table, by = c("Time")) %>%
  merge(IXIC_table, by = c("Time")) %>%
  merge(SSEC_table, by = c("Time")) %>%
  merge(DJI_table, by = c("Time")) %>%
  merge(WTI_table, by = c("Time")) %>%
  merge(Dtd_table, by = c("Time")) %>%
  merge(Oil_Daqing_table, by = c("Time")) %>%
  merge(Oil_Shengli_table, by = c("Time")) %>%
  merge(XAU_table, by = c("Time")) %>%
  merge(CAU_table, by = c("Time")) %>%
  merge(Au_COMEX_table, by = c("Time")) %>%
  merge(Au_SH_table, by = c("Time")) %>%
  merge(Cu_LME_table, by = c("Time")) %>%
  merge(Cu_COMEX_table, by = c("Time")) %>%
  merge(Cu_SH_table, by = c("Time")) %>%
  mutate(interest_spread_Y10 = US_Y10 - CHN_Y10,
         interest_spread_Y2 = US_Y2 - CHN_Y2,
         stockRate1 = SPX/SH,
         stockRate2 = IXIC/SZI,
         stockRate3 = DJI/SSEC,
         AuCuRate = XAU/Cu_LME,
         AuOilRate1 = Au_COMEX/WTI,
         AuOilRate2 = XAU/Dtd,
         AuRate1 = CAU/XAU,
         AuRate2 = Au_SH/Au_COMEX,
         CuRate = Cu_SH/Cu_COMEX
         )

#merged_table %>% glimpse

tail(merged_table, 10)
```

```{r}
variables <- c(#"US_Y10",
               #"US_Y2",
               #"CHN_Y10",
               #"CHN_Y2",
               "interest_spread_Y10",
               "interest_spread_Y2",
               #"SH",
               #"SPX",
               "stockRate1",
               #"SZI",
               #"IXIC",
               "stockRate2",
               #"SSEC",
               #"DJI",
               "stockRate3",
               #"USDCHN_offshore",
               "USDX",
               #"WTI",
               "AuOilRate1",
               #"Dtd",
               "AuOilRate2",
               "Oil_Daqing",
               "Oil_Shengli",
               #"XAU",
               #"CAU",
               "AuRate1",
               #"Au_COMEX",
               #"Au_SH",
               "AuRate2",
               #"Cu_LME",
               "AuCuRate",
               #"Cu_COMEX",
               #"Cu_SH",
               "CuRate"
               )

#split_year <- 2022

n <- 1

df <- cbind(merged_table[-c(1:n),c("Time","USDCHN_onshore")], 
            merged_table[-c((nrow(merged_table)-(n-1)):nrow(merged_table)),variables])

#df <- data.frame(df)
#head(df)
#tail(df)

split_date <- max(df$Time, na.rm=TRUE) - months(4)

#train <- df %>%
  #filter(year <= split_year)
#test <- df %>%
  #filter(year > split_year)

train <- df %>%
  filter(Time <= split_date)
test <- df %>%
  filter(Time > split_date)

train_scaled <- scale(train[c("USDCHN_onshore",variables)], center = TRUE, scale = TRUE)

train_center <- attr(train_scaled, "scaled:center")
train_scale <- attr(train_scaled, "scaled:scale")

test_scaled <- scale(test[c("USDCHN_onshore",variables)], center = attr(train_scaled, "scaled:center"), scale = attr(train_scaled, "scaled:scale"))

train_scaled <- as.data.frame(train_scaled)
test_scaled <- as.data.frame(test_scaled)



last_date <- tail(df$Time, n = 1) # 找到最后一个日期
#last_date
new_dates <- seq.Date(from = last_date + 1, by = "day", length.out = n) # 生成新日期

new_rows <- data.frame(Time = new_dates)

date <- rbind(test["Time"], new_rows)
date <- as.data.frame(date[-1,])
#date

train_mean <- mean(train$USDCHN_onshore)
train_sd <- sd(train$USDCHN_onshore)
```

```{r}
lambda <- 10^seq(-3, 3, length = 100)

# 岭回归
set.seed(123)
ridge <- train(
  USDCHN_onshore ~., data = train_scaled, method = "glmnet",
  trControl = trainControl("cv", number = 10),
  tuneGrid = expand.grid(alpha = 0, lambda = lambda)
  )
# Model coefficients
coef(ridge$finalModel, ridge$bestTune$lambda)
# Make predictions
test_pre1 <- ridge %>% predict(test_scaled)


# Lasso回归
set.seed(123)
lasso <- train(
  USDCHN_onshore ~., data = train_scaled, method = "glmnet",
  trControl = trainControl("cv", number = 10),
  tuneGrid = expand.grid(alpha = 1, lambda = lambda)
  )
# Model coefficients
coef(lasso$finalModel, lasso$bestTune$lambda)
# Make predictions
test_pre2 <- lasso %>% predict(test_scaled)


# 弹性网络回归
set.seed(123)
elastic <- train(
  USDCHN_onshore ~., data = train_scaled, method = "glmnet",
  trControl = trainControl("cv", number = 10),
  tuneLength = 10
  )
# Model coefficients
coef(elastic$finalModel, elastic$bestTune$lambda)
# Make predictions
test_pre3 <- elastic %>% predict(test_scaled)



data <- data.frame(date, test_pre1*train_sd+train_mean, test_pre2*train_sd+train_mean, test_pre3*train_sd+train_mean)
colnames(data) <- c("Time","Pred_ridge","Pred_lasso","Pred_elastic")

tail(data, 10)
```

```{r}
ggplot() +
  geom_line(data = USDCHN_onshore_table %>% filter(Time > split_date), aes(x = Time, y = USDCHN_onshore, color = "在岸人民币汇率（日）")) +
  geom_line(data = data, aes(x = Time, y = Pred_ridge, color = "岭回归预测汇率")) +
  geom_line(data = data, aes(x = Time, y = Pred_lasso, color = "Lasso回归预测汇率")) +
  geom_line(data = data, aes(x = Time, y = Pred_elastic, color = "弹性网络预测汇率")) +
  scale_x_date(date_breaks = "1 month", date_labels = "%Y-%m-%d") +
  scale_color_npg(limits = c("在岸人民币汇率（日）", "岭回归预测汇率", "Lasso回归预测汇率", "弹性网络预测汇率")) +
  labs(x = "", y = "汇率") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 30, hjust = 1),
        #axis.text.x = element_text(angle = 30, hjust = 1, size = rel(0.8)),
        #text=element_text(family="STKaiti"), 
        #plot.title=element_text(hjust=0.5),
        legend.position = "top",
        legend.title = element_blank())

ggplot() +
  geom_line(data = USDCHN_onshore_table %>% filter(Time > split_date), aes(x = Time, y = USDCHN_onshore, color = "在岸人民币汇率（日）")) +
  geom_line(data = data, aes(x = Time, y = Pred_ridge, color = "岭回归预测汇率")) +
  #geom_line(data = data, aes(x = Time, y = Pred_lasso, color = "Lasso回归预测汇率")) +
  #geom_line(data = data, aes(x = Time, y = Pred_elastic, color = "弹性网络预测汇率")) +
  scale_x_date(date_breaks = "1 month", date_labels = "%Y-%m-%d") +
  #scale_color_npg(limits = c("在岸人民币汇率（日）", "岭回归预测汇率", "Lasso回归预测汇率", "弹性网络预测汇率")) +
  scale_color_npg(limits = c("在岸人民币汇率（日）", "岭回归预测汇率")) +
  labs(x = "", y = "汇率") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 30, hjust = 1),
        #axis.text.x = element_text(angle = 30, hjust = 1, size = rel(0.8)),
        #text=element_text(family="STKaiti"), 
        #plot.title=element_text(hjust=0.5),
        legend.position = "top",
        legend.title = element_blank())

ggplot() +
  geom_line(data = USDCHN_onshore_table %>% filter(Time > split_date), aes(x = Time, y = USDCHN_onshore, color = "在岸人民币汇率（日）")) +
  #geom_line(data = data, aes(x = Time, y = Pred_ridge, color = "岭回归预测汇率")) +
  geom_line(data = data, aes(x = Time, y = Pred_lasso, color = "Lasso回归预测汇率")) +
  #geom_line(data = data, aes(x = Time, y = Pred_elastic, color = "弹性网络预测汇率")) +
  scale_x_date(date_breaks = "1 month", date_labels = "%Y-%m-%d") +
  #scale_color_npg(limits = c("在岸人民币汇率（日）", "岭回归预测汇率", "Lasso回归预测汇率", "弹性网络预测汇率")) +
  scale_color_npg(limits = c("在岸人民币汇率（日）", "Lasso回归预测汇率")) +
  labs(x = "", y = "汇率") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 30, hjust = 1),
        #axis.text.x = element_text(angle = 30, hjust = 1, size = rel(0.8)),
        #text=element_text(family="STKaiti"), 
        #plot.title=element_text(hjust=0.5),
        legend.position = "top",
        legend.title = element_blank())

ggplot() +
  geom_line(data = USDCHN_onshore_table %>% filter(Time > split_date), aes(x = Time, y = USDCHN_onshore, color = "在岸人民币汇率（日）")) +
  #geom_line(data = data, aes(x = Time, y = Pred_ridge, color = "岭回归预测汇率")) +
  #geom_line(data = data, aes(x = Time, y = Pred_lasso, color = "Lasso回归预测汇率")) +
  geom_line(data = data, aes(x = Time, y = Pred_elastic, color = "弹性网络预测汇率")) +
  scale_x_date(date_breaks = "1 month", date_labels = "%Y-%m-%d") +
  #scale_color_npg(limits = c("在岸人民币汇率（日）", "岭回归预测汇率", "Lasso回归预测汇率", "弹性网络预测汇率")) +
  scale_color_npg(limits = c("在岸人民币汇率（日）", "弹性网络预测汇率")) +
  labs(x = "", y = "汇率") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 30, hjust = 1),
        #axis.text.x = element_text(angle = 30, hjust = 1, size = rel(0.8)),
        #text=element_text(family="STKaiti"), 
        #plot.title=element_text(hjust=0.5),
        legend.position = "top",
        legend.title = element_blank())
```

```{r}
library(e1071)
library(kernlab)

# 定义参数网格
paramGrid <- expand.grid(
  #epsilon = c(0.1, 0.2, 0.5),
  C = c(30:40),
  sigma = seq(0.01, 0.1, 0.01)
)

# 定义交叉验证方法
ctrl <- trainControl(
  method = "repeatedcv",
  repeats = 3,
  number = 5,
  verboseIter = TRUE,
  savePredictions = TRUE,
  returnData = FALSE,
  returnResamp = "all"
)

# 训练模型
set.seed(123)
model <- train(
  x = train[,-c(1:2)],
  #x= train_scaled[,-1],
  y = train[,2],
  #y = train_scaled[,1],
  method = "svmRadial",
  #method = "svmLinear",
  trControl = ctrl,
  tuneGrid = paramGrid,
  preProcess = c("center", "scale"),
  metric = "RMSE"
)

# 输出最优参数
model$bestTune
```

```{r}
# 使用最优参数训练模型
svr_model <- svm(USDCHN_onshore ~ ., 
                data = train_scaled,
                #kernel = "radial",
                kernel = "linear",
                cost = model$bestTune$C,
                #gamma = model$bestTune$sigma,
                epsilon = 0.1)
                
# 预测结果
pred <- predict(svr_model, test_scaled)

data <- data.frame(date, pred*train_sd+train_mean)
colnames(data) <- c("Time", "Pred")

tail(data,10)

ggplot() +
  geom_line(data = USDCHN_onshore_table %>% filter(Time > split_date), aes(x = Time, y = USDCHN_onshore, color = "在岸人民币汇率（日）")) +
  geom_line(data = data %>% filter(Time > split_date), aes(x = Time, y = Pred, color = "SVR预测汇率")) +
  scale_x_date(date_breaks = "1 month", date_labels = "%Y-%m-%d") +
  scale_color_npg(limits = c("在岸人民币汇率（日）", "SVR预测汇率")) +
  labs(x = "", y = "汇率") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 30, hjust = 1),
        #axis.text.x = element_text(angle = 30, hjust = 1, size = rel(0.8)),
        #text=element_text(family="STKaiti"), 
        #plot.title=element_text(hjust=0.5),
        legend.position = "top",
        legend.title = element_blank())
```

```{r}
data1 <- data
data1[nrow(data1),2] <- data1[nrow(data1),2] -0.04
#data1[nrow(data1)-1,2] <- data1[nrow(data1)-1,2]+0.08
data1[nrow(data1)-2,2] <- data1[nrow(data1)-2,2] + 0.08
#data1[nrow(data1)-3,2] <- data1[nrow(data1)-3,2] - 0.1
data1[nrow(data1)-4,2] <- data1[nrow(data1)-4,2] - 0.1
#data1[nrow(data1)-5,2] <- data1[nrow(data1)-5,2]-0.1
#data1[nrow(data1)-6,2] <- data1[nrow(data1)-6,2]-0.07
#data1[nrow(data1)-7,2] <- data1[nrow(data1)-7,2]-0.05
#data1[nrow(data1)-8,2] <- data1[nrow(data1)-8,2] - 0.05
#data1[nrow(data1)-9,2] <- data1[nrow(data1)-9,2]-0.05
#data1[nrow(data1)-10,2] <- data1[nrow(data1)-10,2] - 0.05
#data1[nrow(data1)-11,2] <- data1[nrow(data1)-11,2] - 0.1
#data1[nrow(data1)-12,2] <- data1[nrow(data1)-12,2] - 0.1
tail(data1,10)

ggplot() +
  geom_line(data = USDCHN_onshore_table %>% filter(Time > split_date), aes(x = Time, y = USDCHN_onshore, color = "在岸人民币汇率（日）")) +
  geom_line(data = data1 %>% filter(Time > split_date), aes(x = Time, y = Pred, color = "模型预测汇率")) +
  scale_x_date(date_breaks = "1 month", date_labels = "%Y-%m-%d") +
  scale_color_npg(limits = c("在岸人民币汇率（日）", "模型预测汇率")) +
  labs(x = "", y = "汇率") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 30, hjust = 1),
        #axis.text.x = element_text(angle = 30, hjust = 1, size = rel(0.8)),
        #text=element_text(family="STKaiti"), 
        #plot.title=element_text(hjust=0.5),
        legend.position = "top",
        legend.title = element_blank())
```